# JAF Python Documentation Configuration

# Project information
site_name: JAF - Juspay Agent Framework (Python)
site_description: A pure functional framework for building AI agents with immutable state and composable tools
site_author: JAF Contributors
site_url: https://xynehq.github.io/jaf-py/
repo_url: https://github.com/xynehq/jaf-py
repo_name: xynehq/jaf-py
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024 JAF Contributors

# Build directories
docs_dir: docs
site_dir: site

# Configuration
theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.png
  logo: assets/logo.png
    
# Page tree
nav:
  - Home: index.md
  - Getting Started:
    - Introduction: getting-started.md
    - Core Concepts: core-concepts.md
    - Examples: examples.md
  - Agent Development:
    - Tools: tools.md
    - Function Composition: function-composition.md
    - Memory System: memory-system.md
    - Model Providers: model-providers.md
  - ADK Production Framework:
    - ADK Overview: adk-overview.md
    - Security Framework: security-framework.md
    - Session Management: session-management.md
    - Error Handling: error-handling.md
  - Examples:
    - Flight Booking System: flight-booking-example.md
  - A2A Protocol:
    - Overview: server-api.md
  - Production Deployment:
    - Infrastructure: infrastructure.md
    - Deployment: deployment.md
    - Validation Suite: validation-suite.md
  - API Reference:
    - API Overview: api-reference.md
    - Server API: server-api.md
  - Advanced Topics:
    - Troubleshooting: troubleshooting.md

# Markdown extensions
markdown_extensions:
  # Python Markdown extensions
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
      
  # PyMdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.gemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: xynehq
      repo: jaf-py
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

# Customization
extra_css:
  - assets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/xynehq/jaf-py
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  version:
    provider: mike

# Documentation directory  
docs_dir: docs